plugins {
  id "com.github.node-gradle.node" version "3.1.1"
}

group = "gov.nih.nci.evs.reportwriter"
version = "2.3.0-SNAPSHOT"

node {
  version = '16.20.2'
  npmVersion = '8.19.4'
  download = true
  workDir = file("${project.buildDir}/node")
  nodeModulesDir = file("${project.projectDir}")
}

// Create a task to run npm build:prod
task npmBuild(type: NpmTask) {
  args = ['run', 'build:prod']
}

// Copy the distribution up to the static folder to complete the build
task build(type: Copy, dependsOn: npmBuild) {
    from 'dist'
    into '../web/src/main/resources/static'
}

