plugins {
  id "com.github.node-gradle.node" version "3.1.1"
}

version '0.0.1'

node {
  version = '22.14.0'
  npmVersion = '10.9.2'
  download = true
  workDir = file("${project.buildDir}/node")
  nodeModulesDir = file("${project.projectDir}")
}
// Create a task to run npm build:prod
task npmBuild(type: NpmTask) {
  args = ['run', 'build:prod']
}

// Make the standard build task depend on our npm build
build.dependsOn(npmBuild)
npmBuild.dependsOn(npmInstall)

