gov:
 nih:
   nci:
    evs:
     reportwriter:
       core:
         templateDirectory: ${RW_TEMPLATE_DIRECTORY:/tmp/templates}
         outputDirectory: ${RW_OUTPUT_DIRECTORY:/tmp/output}
       graphdb:
         url: ${GRAPHDB_URL:http://localhost:5820/NCIT2}
         queryUrl: ${GRAPHDB_QUERY_URL:http://localhost:5820/NCIT2/query}
         username: ${GRAPHDB_USERNAME:ADMIN}
         password: ${GRAPHDB_PASSWORD:ADMIN}
         readTimeout: ${GRAPHDB_READ_TIMEOUT:10000}
         connectTimeout: ${GRAPHDB_CONNECT_TIMEOUT:10000}
         graphName: ${GRAPHDB_GRAPH_NAME:http://NCI_T}

