buildscript {
    ext {
                springBootVersion = '3.3.11'
        }
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://repo.spring.io/release" }
        maven { url "https://repo.spring.io/milestone" }
        maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://repo.maven.apache.org/maven2/org/springframework/boot/org.springframework.boot.gradle.plugin" }
    }

    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
    }

}

plugins {
    id 'org.springframework.boot' version '3.3.11'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'java'
    id 'maven-publish'
}

group = "gov.nih.nci.evs.reportwriter.program"
version = '2.0.3.RELEASE'
sourceCompatibility = 17
targetCompatibility = 17

springBoot {
    mainClass = "gov.nih.nci.evs.reportwriter.program.ReportWriterProgramApplication"
}

repositories {
    mavenLocal()
    mavenCentral() 
    maven { url "https://repo.spring.io/release" }
    maven { url "https://repo.spring.io/milestone" }
    maven { url "https://repo.spring.io/snapshot" }
}


dependencies {

    implementation ('org.springframework.boot:spring-boot-starter')
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'org.springframework.boot:spring-boot-devtools'
//	implementation 'gov.nih.nci.evs.restapi:evsrestapi-util:1.0.0'
	implementation 'commons-cli:commons-cli:1.4'
    implementation "org.apache.poi:poi:5.2.3"
    implementation "org.apache.poi:poi-ooxml:5.2.3"
    implementation 'com.opencsv:opencsv:5.9'
	
//    implementation('gov.nih.nci.evs.reportwriter.core:reportwriter-core:2.0.3-SNAPSHOT')

    implementation project(':core')

    /*
     * Test Dependencies
    */
	testImplementation('org.springframework.boot:spring-boot-starter-test')
}

jar {
    archiveBaseName = project.name
    archiveVersion = project.version
}

test {
    /*
     * Configure gradle to show standard out and standard error
     * of the test JVM(s) on the console
     */
    testLogging.showStandardStreams = true

    /*
     * Activate the 'test' profile
     */
    systemProperties 'spring.profiles.active': 'test'
}

task zipFile(type: Zip) {
    def zipFileRootDirectory = "${project.name}-${project.version}"

    from('src/main/bin') {
        fileMode = 0755
        into "$zipFileRootDirectory/bin"
    }
    from("$buildDir/libs") {
        include '*.jar'
        into "$zipFileRootDirectory/lib"
    }
    rename { String fileName ->
        fileName.replace("-${project.version}", "")
    }
}

bootJar.dependsOn = [jar]
zipFile.dependsOn = [ bootJar ]
build.dependsOn = [ test, bootJar, zipFile ]
publish.dependsOn = [ bootJar, zipFile ]

/*
 * Wrapper task

task wrapper(type: Wrapper) {
    gradleVersion = '4.3.1'
}
*/
